### ISSUE TITLE
Support for rails 4.2

### ISSUE THREAD

**Issue by valtri** [EGI-FCTF/rOCCI-server#106]
Hi,

rOCCI server package in Fedora has stopped working at development branch, because distribution switched to rails 4.2.0. Is it possible to add support for rails 4.2.x?

Quick test with rails 4.2.0 results with:
```
[ 2015-02-14 22:44:04.5283 24610/7f300f696700 Pool2/Implementation.cpp:287 ]: Could not spawn process for application /opt/rOCCI-server: An error occured while starting up the preloader.
  Error ID: e7f6a2da
  Error details saved to: /tmp/passenger-error-VyAfvU.html
  Message from application: The controller-level `respond_to' feature has been extracted to the `responders` gem. Add it to your Gemfile to continue using this feature:
  gem 'responders', '~> 2.0'
Consult the Rails upgrade guide for details. (NoMethodError)
  /opt/rOCCI-server/vendor/bundle/ruby/gems/actionpack-4.2.0/lib/action_controller/metal/mime_responds.rb:10:in `respond_to'
  /opt/rOCCI-server/app/controllers/application_controller.rb:50:in `<class:ApplicationController>'
  /opt/rOCCI-server/app/controllers/application_controller.rb:4:in `<top (required)>'
```
The recommended way of adding 'responders' gem to Gemfile doesn't help (the error remains the same).

**Comment by arax** [comment]
@valtri Could you test it with the pull request referenced above?
