### ISSUE TITLE
Updated AWS-SDK doesn't support direct stubbing with error classes

### ISSUE THREAD

**Issue by arax** [EGI-FCTF/rOCCI-server#116]
An attempt to stub a client method with an error class directly
```ruby
it 'reports correctly on non-existent volume' do
  ec2_dummy_client.stub_responses(:detach_volume, Aws::EC2::Errors::InvalidVolumeNotFound)
  expect{ec2_backend_instance.compute_detach_storage("compute_i-5a8cb7bf_disk_vol-0b15340c")}.to raise_error(Backends::Errors::ResourceNotFoundError)
end
```
will produce
```ruby
Failures:

  1) Backends::Ec2Backend compute .compute_detach_storage reports correctly on non-existent volume
     Failure/Error: expect{ec2_backend_instance.compute_detach_storage("compute_i-5a8cb7bf_disk_vol-0b15340c")}.to raise_error(Backends::Errors::ResourceNotFoundError)
       expected Backends::Errors::ResourceNotFoundError, got #<ArgumentError: wrong number of arguments (0 for 2)> with backtrace:
         # ./lib/backends/ec2/compute.rb:316:in `block in compute_detach_storage'
         # ./lib/backends/ec2/helpers/aws_connect_helper.rb:22:in `rescue_aws_service'
         # ./lib/backends/ec2/compute.rb:315:in `compute_detach_storage'
         # ./lib/backends/helpers/run_before_helper.rb:12:in `call'
         # ./lib/backends/helpers/run_before_helper.rb:12:in `block (2 levels) in run_before'
         # ./spec/lib/backends/ec2_backend_spec.rb:331:in `block (5 levels) in <top (required)>'
         # ./spec/lib/backends/ec2_backend_spec.rb:331:in `block (4 levels) in <top (required)>'
     # ./spec/lib/backends/ec2_backend_spec.rb:331:in `block (4 levels) in <top (required)>'

  2) Backends::Ec2Backend compute .compute_detach_storage reports correctly on non-existent instance
     Failure/Error: expect{ec2_backend_instance.compute_detach_storage("compute_i-5a8cb7bf_disk_vol-0b15340c")}.to raise_error(Backends::Errors::ResourceNotFoundError)
       expected Backends::Errors::ResourceNotFoundError, got #<ArgumentError: wrong number of arguments (0 for 2)> with backtrace:
         # ./lib/backends/ec2/compute.rb:316:in `block in compute_detach_storage'
         # ./lib/backends/ec2/helpers/aws_connect_helper.rb:22:in `rescue_aws_service'
         # ./lib/backends/ec2/compute.rb:315:in `compute_detach_storage'
         # ./lib/backends/helpers/run_before_helper.rb:12:in `call'
         # ./lib/backends/helpers/run_before_helper.rb:12:in `block (2 levels) in run_before'
         # ./spec/lib/backends/ec2_backend_spec.rb:336:in `block (5 levels) in <top (required)>'
         # ./spec/lib/backends/ec2_backend_spec.rb:336:in `block (4 levels) in <top (required)>'
     # ./spec/lib/backends/ec2_backend_spec.rb:336:in `block (4 levels) in <top (required)>'

  3) Backends::Ec2Backend compute .compute_detach_storage reports correctly on non-existent link
     Failure/Error: expect{ec2_backend_instance.compute_detach_storage("compute_i-5a8cb7bf_disk_vol-0b15340c")}.to raise_error(Backends::Errors::ResourceStateError)
       expected Backends::Errors::ResourceStateError, got #<ArgumentError: wrong number of arguments (0 for 2)> with backtrace:
         # ./lib/backends/ec2/compute.rb:316:in `block in compute_detach_storage'
         # ./lib/backends/ec2/helpers/aws_connect_helper.rb:22:in `rescue_aws_service'
         # ./lib/backends/ec2/compute.rb:315:in `compute_detach_storage'
         # ./lib/backends/helpers/run_before_helper.rb:12:in `call'
         # ./lib/backends/helpers/run_before_helper.rb:12:in `block (2 levels) in run_before'
         # ./spec/lib/backends/ec2_backend_spec.rb:341:in `block (5 levels) in <top (required)>'
         # ./spec/lib/backends/ec2_backend_spec.rb:341:in `block (4 levels) in <top (required)>'
     # ./spec/lib/backends/ec2_backend_spec.rb:341:in `block (4 levels) in <top (required)>'

  4) Backends::Ec2Backend network .network_delete copes with operation failing at AWS side
     Failure/Error: expect{ec2_backend_instance.network_delete("vpc-a08b44c5")}.to raise_exception(Backends::Errors::ResourceNotFoundError)
       expected Backends::Errors::ResourceNotFoundError, got #<ArgumentError: wrong number of arguments (0 for 2)> with backtrace:
         # ./lib/backends/ec2/network.rb:183:in `block in network_delete'
         # ./lib/backends/ec2/helpers/aws_connect_helper.rb:22:in `rescue_aws_service'
         # ./lib/backends/ec2/network.rb:182:in `network_delete'
         # ./lib/backends/helpers/run_before_helper.rb:12:in `call'
         # ./lib/backends/helpers/run_before_helper.rb:12:in `block (2 levels) in run_before'
         # ./spec/lib/backends/ec2_backend_spec.rb:537:in `block (5 levels) in <top (required)>'
         # ./spec/lib/backends/ec2_backend_spec.rb:537:in `block (4 levels) in <top (required)>'
     # ./spec/lib/backends/ec2_backend_spec.rb:537:in `block (4 levels) in <top (required)>'
```

**Comment by arax** [comment]
Fixed in #117
