### ISSUE TITLE
How voms authentication is processed?

### ISSUE THREAD

**Issue by giovannifs** [EGI-FCTF/rOCCI-server#129]
Hi all,

I'm not sure if this question should be here, but I'd like to understand better how x509 authentication using voms works. I'm calling the following command and it is not working.

```occi --debug --endpoint http://$ENDPOINT:$PORT --auth x509 --user-cred /tmp/x509up_u1063 --voms --action describe --resource resource_tpl```

The output was:

```
I, [2015-09-17T13:46:08.719185 #20870]  INFO -- : [rOCCI-cli] Starting OCCI client ...
D, [2015-09-17T13:46:08.719816 #20870] DEBUG -- : [rOCCI-cli] Options: #<Hashie::Mash action=:describe attributes={
} auth=#<Hashie::Mash ca_file=nil ca_path="/etc/grid-security/certificates" password="/C=BR/O=ICPEDU/O=UFF" type="x509" user_cert="/tmp/x509up_u1063" user_cert_password="/C=BR/O=ICPEDU/O=UFF" username="anonymous" voms=true> context_vars=nil debug=true dump_model=false endpoint="http://localhost:8182" filter=nil links=nil log=#<Hashie::Mash level=0 logger=#<Occi::Api::Log:0x00000002220388 @core_log=#<Occi::Log:0x00000002220310 @logger=#<Logger:0x000000022202c0 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x00000002220298 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x00000002220248 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x00000002220220 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x000000022201d0>>>>, @log_prefix="[rOCCI-core]", @log_subscriber=#<ActiveSupport::Notifications::Fanout::Subscribers::Timed:0x00000002220068 @pattern="rOCCI-core.log", @delegate=#<Proc:0x00000002220090@/var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/log.rb:26>, @can_publish=false>>, @logger=#<Logger:0x0000000221fff0 @progname=nil, @level=0, @default_formatter=#<Logger::Formatter:0x0000000221ffc8 @datetime_format=nil>, @formatter=nil, @logdev=#<Logger::LogDevice:0x0000000221ff78 @shift_size=nil, @shift_age=nil, @filename=nil, @dev=#<IO:<STDERR>>, @mutex=#<Logger::LogDevice::LogDeviceMutex:0x0000000221ff50 @mon_owner=nil, @mon_count=0, @mon_mutex=#<Mutex:0x0000000221ff00>>>>, @log_prefix="[rOCCI-api]", @log_subscriber=#<ActiveSupport::Notifications::Fanout::Subscribers::Timed:0x0000000221fdc0 @pattern="rOCCI-api.log", @delegate=#<Proc:0x0000000221fde8@/var/lib/gems/1.9.1/gems/occi-core-4.3.2/lib/occi/log.rb:26>, @can_publish=false>> out=#<IO:<STDERR>>> media_type="text/plain,text/occi" mixins=[

] output_format=:plain resource="resource_tpl" timeout=nil>
I, [2015-09-17T13:46:08.719962 #20870]  INFO -- : [rOCCI-cli] Establishing a connection to "http://localhost:8182" ...
opening connection to localhost...
opened
<- "HEAD /-/ HTTP/1.1\r\nAccept: text/plain,text/occi;q=0.2\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.2 OCCI/1.1 ruby-x86_64-linux/1.9.3p0\r\nConnection: close\r\nHost: localhost:8182\r\n\r\n"
-> "HTTP/1.1 401 Unauthorized\r\n"
-> "Content-type: text/plain; charset=UTF-8\r\n"
-> "Content-length: 0\r\n"
-> "Www-authenticate: Keystone uri='http://150.165.85.92:5000'\r\n"
-> "Server: Restlet-Framework/2.2.0\r\n"
-> "Accept-ranges: bytes\r\n"
-> "Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept\r\n"
-> "Date: Thu, 17 Sep 2015 13:46:08 GMT\r\n"
-> "\r\n"
Conn close
D, [2015-09-17T13:46:08.728534 #20870] DEBUG -- : [rOCCI-api] Authentication failed with code 401!
opening connection to localhost...
opened
<- "HEAD /-/ HTTP/1.1\r\nAccept: text/plain,text/occi;q=0.2\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.2 OCCI/1.1 ruby-x86_64-linux/1.9.3p0\r\nConnection: close\r\nHost: localhost:8182\r\n\r\n"
-> "HTTP/1.1 401 Unauthorized\r\n"
-> "Content-type: text/plain; charset=UTF-8\r\n"
-> "Content-length: 0\r\n"
-> "Www-authenticate: Keystone uri='http://150.165.85.92:5000'\r\n"
-> "Server: Restlet-Framework/2.2.0\r\n"
-> "Accept-ranges: bytes\r\n"
-> "Vary: Accept-Charset, Accept-Encoding, Accept-Language, Accept\r\n"
-> "Date: Thu, 17 Sep 2015 13:46:08 GMT\r\n"
-> "\r\n"
Conn close
D, [2015-09-17T13:46:08.734268 #20870] DEBUG -- : [rOCCI-api] #<HTTParty::Response:0x8 parsed_response=nil, @response=#<Net::HTTPUnauthorized 401 Unauthorized readbody=true>, @headers={"content-type"=>["text/plain; charset=UTF-8"], "content-length"=>["0"], "www-authenticate"=>["Keystone uri='http://150.165.85.92:5000'"], "server"=>["Restlet-Framework/2.2.0"], "accept-ranges"=>["bytes"], "vary"=>["Accept-Charset, Accept-Encoding, Accept-Language, Accept"], "date"=>["Thu, 17 Sep 2015 13:46:08 GMT"]}>
opening connection to 150.165.85.92...
opened
<- "POST /v2.0/tokens HTTP/1.1\r\nAccept: application/json\r\nUser-Agent: rOCCI-core/4.3.2 rOCCI-api/4.3.2 OCCI/1.1 ruby-x86_64-linux/1.9.3p0\r\nContent-Type: application/json\r\nConnection: close\r\nHost: 150.165.85.92:5000\r\nContent-Length: 22\r\n\r\n"
<- "{\"auth\":{\"voms\":true}}"
-> "HTTP/1.1 400 Bad Request\r\n"
-> "Date: Thu, 17 Sep 2015 13:49:14 GMT\r\n"
-> "Server: Apache/2.4.7 (Ubuntu)\r\n"
-> "Vary: X-Auth-Token\r\n"
-> "X-Distribution: Ubuntu\r\n"
-> "x-openstack-request-id: req-c1df9fe1-ca8a-49ad-8900-a4098daeb0fb\r\n"
-> "Content-Length: 246\r\n"
-> "Connection: close\r\n"
-> "Content-Type: application/json\r\n"
-> "\r\n"
reading 246 bytes...
-> "{\"error\": {\"message\": \"Expecting to find passwordCredentials in auth - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error.\", \"code\": 400, \"title\": \"Bad Request\"}}"
read 246 bytes
Conn close
D, [2015-09-17T13:46:08.745758 #20870] DEBUG -- : [rOCCI-api] #<HTTParty::Response:0x21c48d0 parsed_response={"error"=>{"message"=>"Expecting to find passwordCredentials in auth - the server could not comply with the request since it is either malformed or otherwise incorrect. The client is assumed to be in error.", "code"=>400, "title"=>"Bad Request"}}, @response=#<Net::HTTPBadRequest 400 Bad Request readbody=true>, @headers={"date"=>["Thu, 17 Sep 2015 13:49:14 GMT"], "server"=>["Apache/2.4.7 (Ubuntu)"], "vary"=>["X-Auth-Token"], "x-distribution"=>["Ubuntu"], "x-openstack-request-id"=>["req-c1df9fe1-ca8a-49ad-8900-a4098daeb0fb"], "content-length"=>["246"], "connection"=>["close"], "content-type"=>["application/json"]}>
F, [2015-09-17T13:46:08.746026 #20870] FATAL -- : [rOCCI-cli] An error occurred! Message: Unable to get a token from Keystone, fallback failed!
/var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/authn_plugins/keystone.rb:73:in `set_auth_token': Unable to get a token from Keystone, fallback failed! (Occi::Api::Client::Errors::AuthnError)
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/authn_plugins/keystone.rb:19:in `setup'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/helpers.rb:39:in `get_auth'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/helpers.rb:56:in `rescue in preauthenticate'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/http/helpers.rb:46:in `preauthenticate'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/client_base.rb:44:in `initialize'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/client/client_http.rb:46:in `initialize'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/dsl.rb:17:in `new'
	from /var/lib/gems/1.9.1/gems/occi-api-4.3.2/lib/occi/api/dsl.rb:17:in `connect'
	from /var/lib/gems/1.9.1/gems/occi-cli-4.3.0.beta.3/bin/occi:55:in `<top (required)>'
	from /usr/local/bin/occi:19:in `load'
	from /usr/local/bin/occi:19:in `<main>'
```

It seems to be trying to use Keystone authentication. 

I remember that using Keystone authentication the rOCCI does a HEAD call at /-/ endpoint, gets the www-Authenticate header and gets a token from there. Then, how voms authentication works? It really should get www-Authenticate? 

I'd would appreciate your help.

**Comment by arax** [comment]
Hi,

for OpenStack-based endpoints, VOMS authentication is handled in Keystone. The negotiation process is the same as for username/password. The only difference is in the use of `{"auth":{"voms":true}}` in the `POST /v2.0/tokens ` request. 

The error message above means that your Keystone is not VOMS-enabled. For more details, see https://keystone-voms.readthedocs.org/en/stable-juno/ as this is not a rOCCI-related (or even OCCI-related) issue.

Cheers
